version: '3.8'

services:
  ansible:
    build: .
    image: network_ansible_env
    container_name: network_ansible_env
    volumes:
      - ./:/ansible
    stdin_open: true # docker run -i
    tty: true        # docker run -t
