name: Continuous Deployment (CD) Network

on:
  # El despliegue real solo debe ocurrir cuando los cambios se fusionan en main
  push:
    branches:
      - main
  # workflow_dispatch permite disparar el despliegue manualmente desde la interfaz web de GitHub
  workflow_dispatch: 

jobs:
  network-deployment:
    name: Despliegue Automatizado de Configuraciones
    runs-on: self-hosted
    
    # Lógica para despliegue condicional (Punto 2.e):
    # El despliegue a producción solo ocurre si el commit NO contiene la etiqueta [skip deploy].
    # Esto da control a los ingenieros para subir cambios urgentes de documentación sin tocar la red.
    if: "!contains(github.event.head_commit.message, '[skip deploy]')"
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Preparar Entorno de Red
        run: |
          python3 -m pip install --upgrade pip --break-system-packages
          # Instalamos las librerías necesarias para que Ansible pueda conectarse a Cisco y MikroTik
          python3 -m pip install ansible paramiko netmiko routeros-api --break-system-packages

      - name: Despliegue en Producción (Aplicación de Configuraciones)
        env:
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
          ANSIBLE_STDOUT_CALLBACK: yaml # Punto 3.a: Formato de log estructurado y legible
          ANSIBLE_FORCE_COLOR: "1"      # Punto 3.a: Forzar colores en los logs de GitHub Actions
        run: |
          echo "Iniciando la automatización de la topología de red..."
          
          # Manejo seguro de credenciales (Punto 2.c): 
          # Creamos el archivo de bóveda temporalmente desde un secreto seguro de GitHub
          echo "$VAULT_PASS" > .vault_pass
          
          echo "Aplicando configuraciones a los routers de GNS3..."
          # Se ejecuta el playbook REAL usando la credencial y -v para mayor detalle en caso de error
          ansible-playbook -i inventory/hosts.yml site.yml -v --vault-password-file .vault_pass
          
          # Limpieza por seguridad para no dejar rastros en el runner local
          rm -f .vault_pass
